### ISSUE TITLE
Problems Creating Account

### ISSUE THREAD

**Issue by paulfears** [MetaMask/keyring-api#101]
When I try to call manageAccount an account this error is raised:
![image_720](https://github.com/MetaMask/keyring-api/assets/25472414/ee48d32c-cc78-416f-a1a0-842f3ab6a484)

typescript says that it's the correct type, but I may be missing something. Here is the object I passed
![image_720](https://github.com/MetaMask/keyring-api/assets/25472414/92ee2523-a6b5-4a29-aca2-7a5e76abf289)

and here is a code snippet from the snap 
```typescript
const account: KeyringAccount = {
      id: uuid(),
      options: options,
      address: options.safeAddress.toString(),
      methods: [
        'eth_signTransaction',
        'eth_sign',
        'eth_signTypedData_v1',
        'eth_signTypedData_v3',
        'eth_signTypedData_v4',
        'personal_sign',
      ],
      type: 'eip155:eoa',
    };
    console.log("account is: ");
    console.log(account);

    this.#wallets[account.id] = { account, salt:options.safeAddress.toString() };
    await this.#saveState();
    console.log("state savved");
    console.log("about to sync accounts");
    await snap.request({
      method: 'snap_manageAccounts',
      params: {
        method: 'createAccount',
        params: { account },
      },
    });
    console.log("manage accounts complete");
    return account;
  }
```

**Comment by danroc** [comment]
Hi @paulfears, the call seems to be correct. Can you share an example of your `options` object?

**Comment by paulfears** [comment]
I want to say options was {name:string, type: string, address: string}, but the I tried an empty object, null, and just {name}, and still got the same error

**Comment by paulfears** [comment]
I was using version 0.2.2v, when the Chrome store version of Metamask Flask supports 0.1.3v.  The value of the name was being incorrectly passed to the snap.
