### ISSUE TITLE
Convert `@metamask/keyring-api` to monorepo 

### ISSUE THREAD

**Issue by gantunesr** [MetaMask/keyring-api#240]
# Description

In order to improve the maintainability of this package and its consumers we should convert it into a monorepo that contains the following packages,

- `keyring-internal-api`
- `keyring-snap-sdk`
- `keyring-snap-client`
- `keyring-api`
- `keyring-utils`
- `accounts-chain-api`
- Move all the keyrings
- Account snaps (SSK, SAAK, Watch-only, BTC)

## Notes

- @danroc will help define the code split between both packages

**Comment by Gudahtt** [comment]
Could we consider moving the keyring API to the core monorepo instead, leaving the SDK here? That might be simpler than setting up a monorepo, and we wanted all of the keyring packages used by extension/mobile to be in core eventually anyway

**Comment by danroc** [comment]
I'd prefer to move to a monorepo, but I'm OK with moving the API to the core monorepo until we have the capacity to work on it.

A breakdown could be as follows:

| Files                            | Package                |
| :------------------------------- | :--------------------- |
| `eth/`                           | `keyring-internal-api` |
| `internal/`                      | `keyring-internal-api` |
| `api.ts`                         | `keyring-api`          |
| `events.ts`                      | `keyring-snap-sdk`     |
| `JsonRpcRequest.ts`              | `keyring-snap-sdk`     |
| `KeyringClient.ts`               | `keyring-snap-client`  |
| `KeyringSnapControllerClient.ts` | `keyring-snap-client`  |
| `KeyringSnapRpcClient.ts`        | `keyring-snap-client`  |
| `rpc-handler.ts`                 | `keyring-snap-sdk`     |
| `snap-utils.ts`                  | `keyring-snap-sdk`     |
| `superstruct.ts`                 | `keyring-utils`        |
| `utils.ts`                       | `keyring-utils`        |

And, pending verification, the dependencies would be:

```mermaid
graph TD
  keyring-api --> keyring-utils
  keyring-internal-api --> keyring-api
  keyring-internal-api --> keyring-utils
  keyring-snap-sdk --> keyring-api
  keyring-snap-sdk --> keyring-utils
  keyring-snap-client --> keyring-api
  keyring-snap-client --> keyring-utils
```

**Comment by gantunesr** [comment]
closed in favor of https://github.com/MetaMask/accounts-planning/issues/556
